[package]
name = "auth-service"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519-dalek = { version = "2.1.1", features = ["rand_core", "pkcs8", "pem"] }
jsonwebtoken = "9.3.1"
rand = "^0.8"
serde = "1.0.219"
