# Special Type: Query
# Dictates all the different query functions your API supports
type Query {
	hello: String # Hello World
	greeting(name: String): String # Greet the user with their name
	getUserByName(username: String): User # Accesses the database and gets a user's name
	allPosts: [Post!]! # Gets every post in the database
}

# Special Type: Mutation
# Mutations are the writes, make changes to your database (create, update, or delete).
type Mutation {
	makePost(username: String, content: String): Post # Creates a new post with a given username and content (and creates a user if there's no associated username)
}

type User {
	id: String
	username: String

	posts: [Post!]!
	likes: [Post!]!
}

type Post {
 id: String
 content: String
 date_posted: String

 author: User
 likes: [User!]!
}

type Like {
	author: User
	post: Post
}